#!/usr/bin/env bash

# Checks pdffonts page by page in a pdf-file. Output to stdout.
#
# Requires: 
#   pdffonts and pdfinfo from poppler-utils
#   Can be installed by 'brew install poppler' (macOS)
#   or 'sudo apt install poppler-utils' (Ubuntu/Debian)
#
# Usage:
#   $ test_embedded_fonts_pdf.sh <pdf-file>

FILE=$1

for i in `seq 1 1 \`pdfinfo $FILE| grep 'Pages' | cut -d: -f2 | sed -e 's/ //g'\``
do
  printf "\nPage $i\n";
  pdffonts -f $i -l $i $FILE;
done
